### PR TITLE
Add license

### LINKED ISSUE #7: Create README.md
Following the README guide here would be very helpful:

https://www.makeareadme.com

### PR DESCRIPTION
**Pull request by b4yc**

### CODE REVIEW

**Comment by RatikKapoor** [comment]
Instead of doing "readme-images" I might make a "docs" folder for documentation so documentation related images could be "docs/images"

**Review by RatikKapoor — CHANGES_REQUESTED** [review]
See comment above re: documentation organization

**Review by RatikKapoor — DISMISSED** [review]
🚢

**Review by RatikKapoor — APPROVED** [review]

**Review by dhyxy — APPROVED** [review]
🚂

**Pull request merged**
