### PR TITLE
Migrate CSS to SCSS

### PR DESCRIPTION
**Pull request by RatikKapoor**
Migrated all CSS to SCSS. SCSS is preferred to CSS as it:
- Is more expressive
- Encourages proper nesting
- Supports better inline documentation
- Is generally is easier to read

*Please merge after approving #10*

### CODE REVIEW

**Review by dhyxy — DISMISSED** [review]
scss to the rescue

**Review by elizetran — DISMISSED** [review]
super sassy

**Comment by RatikKapoor** [comment]
@elizetran @DhyeyLalseta Sorry there were some sudden merge conflicts :(

**Review by elizetran — APPROVED** [review]
still sassy

**Review by dhyxy — APPROVED** [review]
immaculately sassy

**Pull request merged**
