### PR TITLE
Header and Footer First Draft

### PR DESCRIPTION
**Pull request by brooke-k**
Addition of header bar:
- Permanently-displayed header bar added to infotainment system
- Contains battery level, currently aesthetic only. Redux to be completed in a later commit.
- Contains current time, accurate and in AM/PM format
- Contains Bluetooth indicator, currently aesthetic only. Redux to be completed in a later commit. 
- Colour-scheme relevant .scss not updated, header to provide spacing outline for work on the content of other modals only, for now.

Addition of footer bar:
- Inherits previous job of the component TabBar, responsible for routing pages to render modal pages.
- Removed ranges that were previously used in TabBar for volume and fan-speed control. 
- Added settings button in the footer bar, replacing the previous floating action button located on the home page
- Added a home button, currently serves the same purpose as dismissing a page. Routing regarding the home button will be updated in a later commit.

Change in modal size:
- Modal size has been changed from  _90% wide x 80% tall_ to _980px wide x 434px tall_, as per the prototype design version 1.5 on Zeplin. 
- Contents of modal pages have not been updated to reflect this change yet. Current .scss formating of these contents may not render as intended due the modal sizing change.
- Sizing change intended to allow for further development of modal pages to be completed in accordance to new design outlines featured in prototype design version 1.5

### CODE REVIEW

**Review by RatikKapoor — CHANGES_REQUESTED** [review]
image

Seems like header width only works at the screen resolution (no larger) and the header fonts don't seem to load

**Comment by brooke-k** [comment]
> image
> 
> Seems like header width only works at the screen resolution (no larger) and the header fonts don't seem to load

Huh, funky - I'll check that out. 

I know that the header width is limited to the screen resolution, as I was working around the Zeplin prototype outlines, but I can make it dynamically sized if needed. Will just need to update some of the .scss for it, but that's not a problem. 

The fonts are wacky though, so I'll look into why that's happening. It renders alright on my machine, but I'm wondering if that's because I have the font installed locally, so docker knows how to find when I run it. Regardless, it's open source so I'll find a way to get it put into our assets itself, so that there's not an issue with that.

**Comment by brooke-k** [comment]
Used GoogleFont's local hosting of the font to import "Poppins," the font used, variables.scss, so its rendering shouldn't be limited to local installations of it anymore. Let me know if the issue has been corrected.

**Comment by brooke-k** [comment]
Alrighty - all the .scss for the header and footer is now dynamic, so it should scale far better.

Also, before merging I can squash some of those commits so there's less of them there that are redundant.

**Pull request closed without merging**
