### PR TITLE
Added support for customizable notifications.

### PR DESCRIPTION
**Pull request by dylanleclair**
- Extensible parent component
- Can be brought into any component easily 

Example (see Music.tsx for another example):
```                                        
dispatch(
    notifActions.spawnNotification({
    child: new MusicNotif(albumCover, title, artist, !playing), // or any other type of notification
}),
);
```

In the future we could look at (I've also drafted styling for) a Notifications page, but this is a good starting point.

### CODE REVIEW

**Review by brooke-k — APPROVED** [review]
Looks good. Documentation is great. I'm thinking time-spans for notification display will need to be tweaked on a per-use basis, but that can be done when it's implement in more areas. 

👍🏻

**Comment by brooke-k** [comment]
Just noticed - you will need to pull from main to correct the current version of Node. I'll review it again ASAP after that's done.

**Review by brooke-k — APPROVED** [review]
Looks good! 👍🏻

**Comment by dylanleclair** [comment]
Hi @brooke-k, not sure if I ever changed the node version like you mentioned before. Partly because I've been busy but also because I don't really know what you mean? The package.json is the same as main as far as I can tell. Do I still need to change anything?

**Comment by brooke-k** [comment]
Robert went through and just moved things forward to get the Node up to date - no worries

**Review by rjb75 — APPROVED** [review]

**Pull request merged**
